name: Build for Linux

on:
  push:
    tags:
    - 'v*' # Triggers on tags like v1.0.0

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20 # Or your project's Node.js version
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml # Specify the lock file for caching
        registry-url: 'https://registry.npmjs.org' # Ensure correct registry for pnpm

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build Electron app for Linux
      run: pnpm build:linux

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/* # Upload all files in the dist directory
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
