name: Build for Linux

on:
     push:
          branches:
             - main
          paths:
             - 'package.json'
     workflow_dispatch:


jobs:
     build-and-release-linux:
          runs-on: ubuntu-latest

          permissions:
               contents: write

          steps:
             - name: Checkout code
               uses: actions/checkout@v4

             - name: Install pnpm
               uses: pnpm/action-setup@v4
               with:
                    version: latest

             - name: Use Node.js 20
               uses: actions/setup-node@v4
               with:
                    node-version: 20
                    cache: 'pnpm'
                    cache-dependency-path: pnpm-lock.yaml

             - name: Install dependencies
               run: pnpm install

             - name: Build Electron app for Linux
               run: pnpm build:release

             - name: Create Release and Upload Asset
               uses: softprops/action-gh-release@v1
               if: startsWith(github.ref, 'refs/tags/')
               with:
                    files: release/*
               env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
